package be.profacile.savefunds.domain.enums;

public enum AuditAction {
    FINANCIAL_SNAPSHOT_CREATED,
    FINANCIAL_SNAPSHOT_IMPORTED,
    FINANCIAL_DECISION_SIMULATED,
    ACCOUNTANT_NOTE_CREATED,
    VALIDATION_REQUEST_CREATED,
    VALIDATION_DECISION_RECORDED,
    AUDIT_LOG_VIEWED
}